
export const products = [
    {
        id: 0,
        inst:'Institucion',
        op: 'Operativo',
        mod: 'Modalidad',
        nomf: 'Nombre Fase',
        idf: 892,
        f_ini: "01/01/2022",
        f_fin: "02/03/2022",
        f_ing: '01/01/2022',
        f_des: '01/02/2023',
        active: true,
    },
    
        {
            id: 1,
            inst: "Ministerio de Salud Pública de Ecuador",
            op: "Operativo de vacunación masiva en Quito",
            mod: "VSP-VACUNACION-Quito-2022",
            nomf: "Vacunación Quito 2022",
            idf: 101,
            f_ini: "10/03/2022",
            f_fin: "15/04/2022",
            f_ing: "12/03/2022",
            f_des: "01/06/2022",
            active: true
        },
        {
            id: 2,
            inst: "Ministerio del Interior",
            op: "Operativo de seguridad en Guayaquil",
            mod: "ISG-SEGURIDAD-Guayaquil-2023",
            nomf: "Seguridad Guayaquil 2023",
            idf: 102,
            f_ini: "05/05/2023",
            f_fin: "",
            f_ing: "06/05/2023",
            f_des: "20/08/2023",
            active: true
        },
        {
            id: 3,
            inst: "Agencia Nacional de Tránsito",
            op: "Operativo de control de velocidad en la Vía a la Costa",
            mod: "ANT-CONTROL-VELOCIDAD-ViaCosta-2024",
            nomf: "Control de Velocidad Vía Costa 2024",
            idf: 103,
            f_ini: "15/02/2024",
            f_fin: "20/02/2024",
            f_ing: "16/02/2024",
            f_des: "25/02/2024",
            active: true
        },
        {
            id: 4,
            inst: "Ministerio de Inclusión Económica y Social",
            op: "Distribución de alimentos en zonas rurales de Loja",
            mod: "MIES-DISTRIBUCION-ALIMENTOS-Loja-2023",
            nomf: "Alimentos Loja 2023",
            idf: 104,
            f_ini: "01/06/2023",
            f_fin: "15/06/2023",
            f_ing: "03/06/2023",
            f_des: "20/06/2023",
            active: true
        },
        {
            id: 5,
            inst: "Ministerio de Educación",
            op: "Entrega de material escolar en Azuay",
            mod: "ME-MATERIAL-ESCOLAR-Azuay-2023",
            nomf: "Material Escolar Azuay 2023",
            idf: 105,
            f_ini: "10/09/2023",
            f_fin: "30/09/2023",
            f_ing: "12/09/2023",
            f_des: "05/10/2023",
            active: true
        },
        {
            id: 6,
            inst: "Ministerio del Ambiente",
            op: "Operativo de limpieza de playas en Esmeraldas",
            mod: "MA-LIMPIEZA-PLAYAS-Esmeraldas-2023",
            nomf: "Limpieza Playas Esmeraldas 2023",
            idf: 106,
            f_ini: "25/11/2023",
            f_fin: "05/12/2023",
            f_ing: "26/11/2023",
            f_des: "10/12/2023",
            active: true
        },
        {
            id: 7,
            inst: "Cuerpo de Bomberos de Quito",
            op: "Simulacro de evacuación en la zona norte",
            mod: "CBQ-SIMULACRO-EVACUACION-Quito-2024",
            nomf: "Simulacro Quito 2024",
            idf: 107,
            f_ini: "03/03/2024",
            f_fin: "04/03/2024",
            f_ing: "05/03/2024",
            f_des: "10/03/2024",
            active: true
        },
        {
            id: 8,
            inst: "Agencia Nacional de Tránsito",
            op: "Operativo de revisión técnica vehicular en Ambato",
            mod: "ANT-REVISION-TECNICA-Ambato-2024",
            nomf: "Revisión Vehicular Ambato 2024",
            idf: 108,
            f_ini: "01/05/2024",
            f_fin: "15/05/2024",
            f_ing: "02/05/2024",
            f_des: "20/05/2024",
            active: true
        },
        {
            id: 9,
            inst: "Ministerio de Cultura y Patrimonio",
            op: "Campaña de preservación del patrimonio histórico en Cuenca",
            mod: "MCP-PRESERVACION-PATRIMONIO-Cuenca-2023",
            nomf: "Preservación Cuenca 2023",
            idf: 109,
            f_ini: "15/06/2023",
            f_fin: "30/06/2023",
            f_ing: "18/06/2023",
            f_des: "05/07/2023",
            active: true
        },
        {
            id: 10,
            inst: "Ministerio de Agricultura y Ganadería",
            op: "Operativo de asistencia técnica a productores de arroz en Guayas",
            mod: "MAG-ASISTENCIA-ARROZ-Guayas-2023",
            nomf: "Asistencia Guayas 2023",
            idf: 110,
            f_ini: "01/07/2023",
            f_fin: "15/07/2023",
            f_ing: "02/07/2023",
            f_des: "20/07/2023",
            active: true
        },
        {
            id: 11,
            inst: "Ministerio de Relaciones Exteriores",
            op: "Operativo de asistencia a migrantes ecuatorianos en Colombia",
            mod: "MRE-ASISTENCIA-MIGRANTES-Colombia-2023",
            nomf: "Asistencia Migrantes Colombia 2023",
            idf: 111,
            f_ini: "15/08/2023",
            f_fin: "15/09/2023",
            f_ing: "20/08/2023",
            f_des: "30/09/2023",
            active: true
        },
        {
            id: 12,
            inst: "Ministerio de Defensa Nacional",
            op: "Operativo de patrullaje en zonas fronterizas del Carchi",
            mod: "MDN-PATRULLAJE-Carchi-2023",
            nomf: "Patrullaje Carchi 2023",
            idf: 112,
            f_ini: "10/10/2023",
            f_fin: "01/11/2023",
            f_ing: "12/10/2023",
            f_des: "10/11/2023",
            active: true
        },
        {
            id: 13,
            inst: "Ministerio de Turismo",
            op: "Campaña de promoción turística en la Amazonía",
            mod: "MT-PROMOCION-TURISTICA-Amazonía-2023",
            nomf: "Promoción Turística Amazonía 2023",
            idf: 113,
            f_ini: "01/04/2023",
            f_fin: "15/04/2023",
            f_ing: "05/04/2023",
            f_des: "20/04/2023",
            active: true
        },
        {
            id: 14,
            inst: "Ministerio de Trabajo",
            op: "Revisión de condiciones laborales en empresas de Pichincha",
            mod: "MT-REVISION-CONDICIONES-Pichincha-2023",
            nomf: "Condiciones Laborales Pichincha 2023",
            idf: 114,
            f_ini: "10/12/2023",
            f_fin: "20/12/2023",
            f_ing: "12/12/2023",
            f_des: "25/12/2023",
            active: true
        },
        {
            id: 15,
            inst: "Comisión Nacional de Tránsito",
            op: "Operativo de control de alcoholemia en Riobamba",
            mod: "CNT-CONTROL-ALCOHOLEMIA-Riobamba-2024",
            nomf: "Control Alcoholemia Riobamba 2024",
            idf: 115,
            f_ini: "15/03/2024",
            f_fin: "30/03/2024",
            f_ing: "18/03/2024",
            f_des: "05/04/2024",
            active: true
        },
        {
            id: 16,
            inst: "Ministerio de Obras Públicas",
            op: "Rehabilitación de vías en la provincia de Tungurahua",
            mod: "MOP-REHABILITACION-VIAS-Tungurahua-2023",
            nomf: "Rehabilitación Tungurahua 2023",
            idf: 116,
            f_ini: "01/05/2023",
            f_fin: "01/06/2023",
            f_ing: "03/05/2023",
            f_des: "10/06/2023",
            active: true
        },
        {
            id: 17,
            inst: "Secretaría Nacional de Gestión de Riesgos",
            op: "Operativo de rescate en zonas afectadas por el sismo en Manabí",
            mod: "SNGR-RESCATE-SISMO-Manabí-2023",
            nomf: "Rescate Manabí 2023",
            idf: 117,
            f_ini: "25/04/2023",
            f_fin: "30/04/2023",
            f_ing: "28/04/2023",
            f_des: "05/05/2023",
            active: true
        },
        {
            id: 18,
            inst: "Ministerio de Justicia, Derechos Humanos y Cultos",
            op: "Revisión de derechos humanos en centros penitenciarios",
            mod: "MJDH-REVISION-DERECHOS-HUMANOS-2023",
            nomf: "Revisión DDHH Penitenciarios 2023",
            idf: 118,
            f_ini: "01/08/2023",
            f_fin: "15/08/2023",
            f_ing: "03/08/2023",
            f_des: "20/08/2023",
            active: true
        },
        {
            id: 19,
            inst: "Instituto Nacional de Estadística y Censos",
            op: "Censo poblacional en zonas rurales de Ecuador",
            mod: "INEC-CENSO-POPULACIONAL-ZONAS-RURALES-2023",
            nomf: "Censo Rural Ecuador 2023",
            idf: 119,
            f_ini: "10/06/2023",
            f_fin: "20/06/2023",
            f_ing: "12/06/2023",
            f_des: "25/06/2023",
            active: true
        },
        {
            id: 20,
            inst: "Ministerio de Transporte y Obras Públicas",
            op: "Rehabilitación de puentes en la provincia de Loja",
            mod: "MTO-REHABILITACION-PUENTES-Loja-2023",
            nomf: "Rehabilitación Puentes Loja 2023",
            idf: 120,
            f_ini: "01/07/2023",
            f_fin: "15/07/2023",
            f_ing: "03/07/2023",
            f_des: "10/07/2023",
            active: true
        },
        {
            id: 21,
            inst: "Secretaría de Comunicación",
            op: "Campaña informativa sobre prevención de riesgos naturales",
            mod: "SC-CAMPANA-PREVENCIÓN-RIESGOS-2024",
            nomf: "Prevención Riesgos Naturales 2024",
            idf: 121,
            f_ini: "05/01/2024",
            f_fin: "15/01/2024",
            f_ing: "07/01/2024",
            f_des: "20/01/2024",
            active: true
        },
        {
            id: 22,
            inst: "Ministerio de Salud Pública",
            op: "Control de epidemias en la provincia de Loja",
            mod: "MSP-CONTROL-EPIDEMIAS-Loja-2023",
            nomf: "Control Epidemias Loja 2023",
            idf: 122,
            f_ini: "15/05/2023",
            f_fin: "25/05/2023",
            f_ing: "17/05/2023",
            f_des: "30/05/2023",
            active: true
        },
        {
            id: 23,
            inst: "Agencia Nacional de Tránsito",
            op: "Campaña de seguridad vial en el sur de Quito",
            mod: "ANT-SEGUIMIENTO-SUR-Quito-2023",
            nomf: "Seguridad Vial Sur Quito 2023",
            idf: 123,
            f_ini: "05/11/2023",
            f_fin: "15/11/2023",
            f_ing: "06/11/2023",
            f_des: "10/11/2023",
            active: true
        },
        {
            id: 24,
            inst: "Comisión Nacional de Tránsito",
            op: "Operativo de inspección de vehículos de carga en Pichincha",
            mod: "CNT-INSPECCION-CARGA-Pichincha-2023",
            nomf: "Inspección Carga Pichincha 2023",
            idf: 124,
            f_ini: "15/05/2023",
            f_fin: "31/05/2023",
            f_ing: "16/05/2023",
            f_des: "10/06/2023",
            active: true
        },
        {
            id: 25,
            inst: "Ministerio de Defensa Nacional",
            op: "Operativo de patrullaje en la zona de Tena",
            mod: "MDN-PATRULLAJE-Tena-2023",
            nomf: "Patrullaje Tena 2023",
            idf: 125,
            f_ini: "01/12/2023",
            f_fin: "15/12/2023",
            f_ing: "02/12/2023",
            f_des: "20/12/2023",
            active: true
        }
    
    
    
    
    
    
];
